name: Instagram Safe Female Bot

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-insta-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 35

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          # CHANGE THIS: 3.9 ki jagah 3.10 karein
          python-version: '3.10' 

      - name: Install Libraries
        run: |
          pip install instagrapi pytz requests

      - name: Run Bot Script
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          SESSION_ID: ${{ secrets.SESSION_ID }}
        run: timeout 25m python m.py || echo "Cycle completed or timed out"
        
